let mystr = "It's hard to say who is right in this matter";
let result0 = mystr.indexOf("a", 17);
console.log(result0);
let result1 = mystr.includes("righT");
console.log(result1);
let result2 = mystr.indexOf("who");
let result3 = mystr.slice(17, 21);
console.log(result3);
let result4 = mystr.charAt(mystr.length - 1);
console.log(result4);
